drop TABLE INVITACION_CONFIRMACION
drop TABLE INVITACION
drop TABLE EVENTO
CREATE TABLE EVENTO(
ID_EVENTO INT IDENTITY(1,1)
,ANFITRION VARCHAR(500)
,FECHA DATETIME 
,CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO)
)

CREATE TABLE INVITACION(
	ID_INVITACION INT IDENTITY(1,1)
	,ID_EVENTO INT 
	,NOMBRE VARCHAR(500)
	,ADULTOS INT
	,MENORES INT
	,FECHA_EXPIRACION DATETIME
	,ESTADO VARCHAR(1)--P: PENDIENTE DE CONFIRMAR, C: CONFIRMADA, 
	,CONSTRAINT PK_INVITACION PRIMARY KEY (ID_INVITACION)
	,CONSTRAINT FK_INVITACION_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
)

CREATE TABLE INVITACION_CONFIRMACION(
	ID_INVITACION INT NOT NULL
	,ADULTOS_CONFIRMADOS INT
	,MENORES_CONFIRMADOS INT
	,CONSTRAINT PK_INVITACION_CONFIRMACION PRIMARY KEY (ID_INVITACION)
	,CONSTRAINT FK_INVITACION_CONFIRMACION_INVITACION FOREIGN KEY (ID_INVITACION) REFERENCES INVITACION(ID_INVITACION)
)

select * from EVENTO
insert into EVENTO values ('Mynor y Bernarda','20241214 15:00:00')
select * from INVITACION
select * from INVITACION_CONFIRMACION

insert into INVITACION values (2,'Invitado 1',2,2,'20240928 23:00:00','P')

delete from INVITACION_CONFIRMACION

update INVITACION set ESTADO = 'P';